apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: user-api:v1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: prod
spec:
  selector:
    app: user-api
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
